### ISSUE TITLE
Add regex support for individual websites 

### ISSUE THREAD

**Issue by manu-chroma** [manu-chroma/username-availability-checker#11]
It shows not available for usernames which might not be possible to even create due to that particular websites limitations for username.

Add **not possible** for such usernames.

Can be fixed using regex for each website.

**Comment by jayvdb** [comment]
See https://github.com/WebBreacher/WhatsMyName

**Comment by manu-chroma** [comment]
Ideally, I'd like to add regex check for individual websites in: https://github.com/manu-chroma/username-availability-checker/blob/master/username_api.py

There is a very rudimentary check implemented in the frontend at: https://github.com/manu-chroma/username-availability-checker/blob/master/templates/form.html#L36

**Comment by manu-chroma** [comment]
> See WebBreacher/WhatsMyName

@jayvdb I don't think their json data contains anything related to regex.

**Comment by manu-chroma** [comment]
Task claimed by @andrewda

**Comment by jayvdb** [comment]
@manu-chroma , a username patter could be added to https://github.com/WebBreacher/WhatsMyName/blob/master/web_accounts_list.json .  They also need it, for the same reason this project needs it.

Their dataset contains everything that this project supports, except GitLab, which should be very easy to solve.

**Comment by jayvdb** [comment]
https://github.com/manu-chroma/username-availability-checker/issues/25 was spawned from here
