### ISSUE TITLE
If user name is available, take user to the Sign Up page

### ISSUE THREAD

**Issue by ayan-b** [manu-chroma/username-availability-checker#120]
If a username is available, on clicking the icon it should take the user to the Sign Up page of the respective site.

**Comment by jayvdb** [comment]
Add a `signup:` key in `websites.yml` with the signup url, with url parameters as template variables, for a few sites.

Once a few are done, submit a PR.

Then we'll create new issues for adding signup support to the remainder of the websites, and other participants can help.
