### ISSUE TITLE
Fix CSS styling

### ISSUE THREAD

**Issue by kx-chen** [manu-chroma/username-availability-checker#130]
CSS in `static/css/main.css` has bad spacing after the `:` (separating the property from the style). Fix all the CSS rules to have a space after the `:`
Newcomer?

**Comment by jayvdb** [comment]
Also add a rule to .coafile to enforce this, and add the linter to the CI environment

**Comment by manu-chroma** [comment]
am I missing something in the css rule in https://github.com/manu-chroma/username-availability-checker/blob/master/.coafile

**Comment by jayvdb** [comment]
Ya, we need a linter which does deep inspection of the .css contents ... I dont want to give away too many hints ;-)
