### ISSUE TITLE
Unreliable results for facebook.com 

### ISSUE THREAD

**Issue by manu-chroma** [manu-chroma/username-availability-checker#20]
If a user has set his/her profile as not visible to search engines, then it will return 404 page when accessing the profile without logging into facebook. 

Very few profiles fall into this case judging by the small sample of profiles I was testing on. 
But still makes results unreliable, disabling facebook check for now.

![image](https://user-images.githubusercontent.com/12952080/33802879-fd41b538-dda7-11e7-8d2b-992fbcf5fbc9.png)

**Comment by jayvdb** [comment]
I suggest you try mobile; that often works when the normal website does not.
