### ISSUE TITLE
Add support for OpenHub and DeviantArt

### ISSUE THREAD

**Issue by manu-chroma** [manu-chroma/username-availability-checker#24]
OpenHub: ``https://www.openhub.net/accounts/<username>``
Devianart: ``https://<username>.deviantart.com/``

See: 
- https://github.com/manu-chroma/username-availability-checker/blob/master/username_api.py
- https://github.com/manu-chroma/username-availability-checker/blob/master/templates/status.html

**Comment by seeeturtle** [comment]
please assign me

**Comment by manu-chroma** [comment]
@seeeturtle is working on this task now
