### ISSUE TITLE
Add Travis testing using pytest

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#31]
Run tests to confirm that the algorithms used produce correct results for existing known usernames and non-existing (but valid usernames).

The usernames for each case need to be stored in a test data file.

If the known non-existent username becomes existent according to the algorithm, it may mean the username has become taken, or the algorithm used has become invalid.
Include a basic random nonsense username generator to try again using a different username.
If the nonsense username is found to be non-existent, the test should still error, but provide a message which suggests that the nonsense username should be manually checked and used as a replacement in the test data.

**Comment by manu-chroma** [comment]
We should have async requests in tests to speed up checking, otherwise tests will be slow and non-scalable.

**Comment by manu-chroma** [comment]
@jayvdb just a wild idea, would it make sense to write username tests in js, given how easy it would be to make async calls and assert accordingly?

I think it would become overly complex and cumbersome when coming to python

**Comment by manu-chroma** [comment]
also, this issue is assigned to @andrewda

**Comment by andrewda** [comment]
Just wrote about 3-4 tests for each platform and it takes less than 8 seconds for all of them to pass. Async requests probably aren't necessary.

**Comment by manu-chroma** [comment]
Interesting. Feel free to create a [WIP] PR
We can discuss more tomorrow.
