### ISSUE TITLE
Fetch avatar URLs from each website

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#35]
Most of the websites have some sort of avatar which can be obtained and included in the results for 'Taken' names.

This will help to see whether a username has a consistent avatar across various platforms, which can be used as a proxy to guess that they are taken by the same person.

**Comment by manu-chroma** [comment]
``meta  property="og:image"`` contains image url at a lot of times. check that out

**Comment by jayvdb** [comment]
Should we make this a backend only task to begin with?
Then you can think about the UI a bit, and then create another task to do the UI?

**Comment by manu-chroma** [comment]
Yes, that's what I had in mind. 
Backend will start passing avatar links and then we can figure out the frontend part

**Comment by nalinbhardwaj** [comment]
Is there a reason to rely on metadata only? Why not add proper image fetching for valid usernames as link templates to [websites.yml](https://github.com/manu-chroma/username-availability-checker/blob/master/websites.yml)(and use it)

**Comment by manu-chroma** [comment]
@nalinbhardwaj they're not available for all websites, but yes if we can get them, they're a better option to handle image fetch.  

Apart from this, in case of fb, we'll have to extract ``userid`` from the profile source anyways to use this url.

**Comment by manu-chroma** [comment]
Might be helpful: ``https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary``
