### ISSUE TITLE
Add more test parameterisation

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#36]
https://github.com/manu-chroma/username-availability-checker/pull/32 added pytest , however the test module still has lots of duplicated logic.

There are many advanced [pytest data plugins](https://pypi.python.org/pypi?%3Aaction=search&term=pytest+data&submit=search) which allow more data parameterisation that the core pytest plugins.

Implement one which removes the duplication in the test module.

**Comment by jayvdb** [comment]
... which would have prevented copy/paste errors like https://github.com/manu-chroma/username-availability-checker/pull/34#discussion_r157597839 ;-)

**Comment by jayvdb** [comment]
The infrastructure was already added in #42, so this is now a moderately easy task, of re-applying the same approaches used there.

**Comment by seeeturtle** [comment]
can you assign me here?

**Comment by manu-chroma** [comment]
assigned to @seeeturtle 

Make sure to get your other PR merged soon.
