### ISSUE TITLE
Add Gravatar support

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#37]
Gravatar supports profile usernames.

**Comment by seeeturtle** [comment]
this issue is related with getting profile image of openhub since it set profile image as gravatar.

**Comment by pavi2410** [comment]
I can do this. I claimed this task on GCI.

**Comment by jayvdb** [comment]
@pavi2410 , great, come onto https://coala.zulipchat.com/#narrow/stream/gci/subject/username-availability if you need a hand

**Comment by pavi2410** [comment]
Isn't there any problem if I parse the user page to get avatar image?

**Comment by jayvdb** [comment]
It is ok if you parse the page to get the avatar, but isnt ideal.
Ideally we use the gravatar API, but that can be done in a different task.
See [pypi](https://pypi.python.org/pypi?%3Aaction=search&term=gravatar&submit=search) for some packages which may help.

**Comment by pavi2410** [comment]
Let's start from first. What should I do?

**Comment by manu-chroma** [comment]
Check:
https://github.com/manu-chroma/username-availability-checker/pull/72#issuecomment-356487675
https://github.com/manu-chroma/username-availability-checker/pull/72#issue-287167838

you need to fix your commit message and I think we will be able to merge then.

**Comment by pavi2410** [comment]
Should I add a method to fetch gravatar image from username? If it succeeds, then return the gravatar image, else scrape the image. But we cannot guarantee that a single person has the same username in different services. For eg, if a person A has username `XYZ` in open hub, but the same username on gravatar is of person B.

**Comment by manu-chroma** [comment]
what you've done is good to go for now. just fix the commit message to include the issues you addressed. https://github.com/manu-chroma/username-availability-checker/pull/74#issuecomment-357148292

> But we cannot guarantee that a single person has the same username in different services. For eg, if a person A has username XYZ in open hub, but the same username on gravatar is of person B.

that's is why we won't be doing this. integrating gravatar's from https://en.gravatar.com/ will be considered in a separate issue.
