### ISSUE TITLE
Display logo and website name for each website

### ISSUE THREAD

**Issue by blazeu** [manu-chroma/username-availability-checker#50]
Currently it is not clear which website is which ..

![image](https://user-images.githubusercontent.com/1438859/34361961-b0ce1334-eaa1-11e7-9734-a9ec66485317.png)

**Comment by manu-chroma** [comment]
https://username-check.herokuapp.com/?username=blazeu

Logos and website name(tooltip) work totally fine for me. Can you check your console for errors?

**Comment by blazeu** [comment]
`GET https://use.fontawesome.com/538119ba0a.js net::ERR_NAME_NOT_RESOLVED`

Yup, the error seems to come from me ([and everyone?](http://downforeveryoneorjustme.com/use.fontawesome.com))

**Comment by manu-chroma** [comment]
``https://use.fontawesome.com/538119ba0a.js`` works for me
