### ISSUE TITLE
Add support for medium

### ISSUE THREAD

**Issue by manu-chroma** [manu-chroma/username-availability-checker#58]
URL: ``https://medium.com/@<username>``

**Comment by seeeturtle** [comment]
@manu-chroma, it seems medium is using social accounts(google, facebook) for creating new account now.
Should we need to support medium?

**Comment by seeeturtle** [comment]
Oops, sorry.
I've closed the issue by mistake.

**Comment by manu-chroma** [comment]
every user still has a username regardless, AFAIK

**Comment by seeeturtle** [comment]
yeah, you're right.
I've just found that it only allows letter, number, dot(.), and underbar(_).
and possible username length is 1 to 15 for now.
but there is some username that overs this length.
for example, https://medium.com/@aaaaaaaaaaaaaaaa
this has 16 letters.

**Comment by seeeturtle** [comment]
@manu-chroma, I'm little concerned that it deletes inactive accounts.
What account can we use for `constant_account`?

**Comment by seeeturtle** [comment]
I'll just use medium staff account (https://medium.com/@MediumStaff).
I hope it's constant account.

**Comment by manu-chroma** [comment]
that's a good choice

**Comment by seeeturtle** [comment]
https://github.com/manu-chroma/username-availability-checker/commit/b1baf7b9e15a193320febadad93c5c6c12d08e89
