### ISSUE TITLE
Allow users to check availability directly from the URL

### ISSUE THREAD

**Issue by duttaditya18** [manu-chroma/username-availability-checker#61]
**Example :**
If someone goes to `https://username-check.herokuapp.com/username`. It should directly check for `username`'s availability.

**Comment by manu-chroma** [comment]
This query string works: ``https://username-check.herokuapp.com/?username=<username>``

But I agree we can have a more user friendly route for checking.

**Comment by duttaditya18** [comment]
@manu-chroma That query string can be used to generate a JSON.

**Comment by manu-chroma** [comment]
@duttaditya18 I don't understand what you by that

**Comment by duttaditya18** [comment]
@manu-chroma I mean we can generate a JSON for each query.

**Comment by manu-chroma** [comment]
This is what we do atm: https://github.com/manu-chroma/username-availability-checker/blob/master/frontend.py#L18

Adding ``https://username-check.herokuapp.com/username`` route should be trivial task here.
