### ISSUE TITLE
Add avatar support for OpenHub

### ISSUE THREAD

**Issue by manu-chroma** [manu-chroma/username-availability-checker#63]
Relavent files to make changes to:
- websites.yml
- username_api.py
- avatar testing

**Comment by seeeturtle** [comment]
@manu-chroma openhub always set avatar image as gravatar.

**Comment by seeeturtle** [comment]
Closed by https://github.com/manu-chroma/username-availability-checker/commit/663c2c4d659d9e78fbc4cab1f74378fd32e819e5

**Comment by seeeturtle** [comment]
Closed by https://github.com/manu-chroma/username-availability-checker/commit/663c2c4d659d9e78fbc4cab1f74378fd32e819e5
