### ISSUE TITLE
OpenHub site error is detected as taken

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#66]
https://www.openhub.net/accounts/45345345 currently responds with "The Black Duck Open Hub is currently offline"

This actually happens quite a bit, so we should have a way to detect and inform the user that OpenHub cant be checked at the moment.

**Comment by seeeturtle** [comment]
@jayvdb, there was similar thing with connect.opensuse.org. We should add some code that check if website is unable to use. for example, if taken username is available then the website is unable to use.

**Comment by jayvdb** [comment]
> for example, if taken username is available then the website is unable to use.

Very interesting idea.

**Comment by manu-chroma** [comment]
+1 for this idea and easy to implement too.

**Comment by seeeturtle** [comment]
travis build: https://travis-ci.org/manu-chroma/username-availability-checker/builds/325793324
this was a build while connect.opensuse.org was down

**Comment by manu-chroma** [comment]
when any website goes down unexpectedly, we have error handling for that at https://github.com/manu-chroma/username-availability-checker/blob/master/templates/status.html#L46

**Comment by seeeturtle** [comment]
not working for websites that reponse 200 even website is down

**Comment by seeeturtle** [comment]
@jayvdb, can you rename the issue?

**Comment by seeeturtle** [comment]
@jayvdb, can you rename the issue?
