### ISSUE TITLE
Move websites.yaml into python classes

### ISSUE THREAD

**Issue by seeeturtle** [manu-chroma/username-availability-checker#75]
Even they are attributes of a same website, They are separated from each other.
I think we should make top level class that describes attributes for website,
and make subclasses for each website.

What do you think about this?

**Comment by manu-chroma** [comment]
cc: @jayvdb

**Comment by jayvdb** [comment]
No.  It is data.  Re-usable across language, and in different domains.

If you want, generate python classes from the data.

**Comment by seeeturtle** [comment]
got it :)
