### ISSUE TITLE
Optimise for mobile

### ISSUE THREAD

**Issue by gyanl** [manu-chroma/username-availability-checker#8]
Currently it's pretty bad on mobile.

**Comment by manu-chroma** [comment]
Much better optimized for mobile now. Can close this after the card implementation of the second page.

**Comment by gyanl** [comment]
I think it's actually pretty decent on mobile now - cards not really necessary since they'll just add padding and you'll have to scroll more to see everything.

**Comment by manu-chroma** [comment]
Closing it then.
