### ISSUE TITLE
Add keybase.io

### ISSUE THREAD

**Issue by jayvdb** [manu-chroma/username-availability-checker#97]
http://keybase.io provides verified links to other identities, so it is a good account to have registered early.

**Comment by manu-chroma** [comment]
maybe we can use api in this case, since no key is required and looks straight forward to use 
API lookup: https://keybase.io/docs/api/1.0/call/user/lookup
Eg: https://keybase.io/_/api/1.0/user/lookup.json?usernames=jayvdb
